name: Bug Report
description: Report a bug or issue with the profile
title: "[BUG] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report an issue! Please fill out the information below.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the issue you encountered
    validations:
      required: true

  - type: textarea
    id: location
    attributes:
      label: Location
      description: Where did you encounter this issue?
      placeholder: e.g., Line 50 of README.md, or specific section
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe what should happen instead
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: Screenshots, links, etc.
    validations:
      required: false
