name: Feature Request
description: Suggest an improvement for the profile
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting an improvement! Please provide details below.

  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: Describe the feature or improvement you'd like to see
      placeholder: What would you like to see added or changed?
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why would this be useful?
      placeholder: Explain the benefits of this feature
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Are there any alternative approaches?
      placeholder: Describe any alternative solutions you've considered
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the feature request here
      placeholder: Links, examples, mockups, etc.
    validations:
      required: false
