# GitHub Star Organization Categories Configuration
# This file defines the categories and their matching criteria for organizing starred repositories

categories:
  "Development & Programming":
    description: "General programming tools, frameworks, and development resources"
    keywords:
      - "programming"
      - "development"
      - "framework"
      - "library"
      - "sdk"
      - "api"
      - "development-tools"
      - "coding"
    topics:
      - "javascript"
      - "python"
      - "java"
      - "cpp"
      - "csharp"
      - "golang"
      - "rust"
      - "typescript"
      - "php"
      - "ruby"
      - "swift"
      - "kotlin"
      - "dart"
      - "scala"
      - "programming"
      - "development"
      - "framework"
      - "library"
    languages:
      - "JavaScript"
      - "Python"
      - "Java"
      - "C++"
      - "C#"
      - "Go"
      - "Rust"
      - "TypeScript"
      - "PHP"
      - "Ruby"
      - "Swift"
      - "Kotlin"
      - "Dart"
      - "Scala"

  "ML & AI":
    description: "Machine Learning, Artificial Intelligence, and Data Science projects"
    keywords:
      - "machine-learning"
      - "artificial-intelligence"
      - "deep-learning"
      - "neural-network"
      - "data-science"
      - "tensorflow"
      - "pytorch"
      - "scikit-learn"
      - "ai"
      - "ml"
      - "nlp"
      - "computer-vision"
      - "data-analysis"
    topics:
      - "machine-learning"
      - "artificial-intelligence"
      - "deep-learning"
      - "neural-networks"
      - "data-science"
      - "tensorflow"
      - "pytorch"
      - "scikit-learn"
      - "ai"
      - "ml"
      - "nlp"
      - "computer-vision"
      - "data-analysis"
      - "jupyter-notebook"
      - "pandas"
      - "numpy"

  "Tools & Utilities":
    description: "Development tools, utilities, and productivity software"
    keywords:
      - "tool"
      - "utility"
      - "cli"
      - "command-line"
      - "productivity"
      - "automation"
      - "script"
      - "helper"
      - "toolkit"
    topics:
      - "cli"
      - "command-line"
      - "tool"
      - "utility"
      - "automation"
      - "productivity"
      - "script"
      - "toolkit"
      - "developer-tools"
      - "build-tool"

  "DevOps & Cloud":
    description: "DevOps tools, cloud infrastructure, and deployment resources"
    keywords:
      - "devops"
      - "cloud"
      - "kubernetes"
      - "docker"
      - "terraform"
      - "ansible"
      - "ci-cd"
      - "deployment"
      - "infrastructure"
      - "monitoring"
      - "aws"
      - "azure"
      - "gcp"
    topics:
      - "devops"
      - "cloud"
      - "kubernetes"
      - "docker"
      - "terraform"
      - "ansible"
      - "ci-cd"
      - "continuous-integration"
      - "continuous-deployment"
      - "infrastructure"
      - "monitoring"
      - "aws"
      - "azure"
      - "google-cloud"
      - "containerization"

  "Learning & Education":
    description: "Educational resources, tutorials, and learning materials"
    keywords:
      - "tutorial"
      - "learning"
      - "education"
      - "course"
      - "guide"
      - "example"
      - "demo"
      - "sample"
      - "documentation"
      - "book"
      - "cheatsheet"
    topics:
      - "tutorial"
      - "learning"
      - "education"
      - "course"
      - "guide"
      - "example"
      - "demo"
      - "documentation"
      - "cheatsheet"
      - "awesome-list"
      - "resources"

  "Games & Entertainment":
    description: "Game development, entertainment projects, and fun applications"
    keywords:
      - "game"
      - "gaming"
      - "entertainment"
      - "fun"
      - "puzzle"
      - "arcade"
      - "unity"
      - "unreal"
      - "godot"
    topics:
      - "game"
      - "game-development"
      - "gaming"
      - "unity"
      - "unreal-engine"
      - "godot"
      - "pygame"
      - "entertainment"
      - "arcade"
      - "puzzle"
      - "2d-game"
      - "3d-game"

  "Open Source Projects":
    description: "Notable open source projects and community-driven initiatives"
    keywords:
      - "open-source"
      - "community"
      - "hacktoberfest"
      - "contribution"
      - "collaborative"
    topics:
      - "open-source"
      - "hacktoberfest"
      - "community"
      - "collaboration"
      - "foss"

  "Portfolio & Showcase":
    description: "Portfolio projects, personal websites, and showcase repositories"
    keywords:
      - "portfolio"
      - "personal"
      - "website"
      - "showcase"
      - "profile"
      - "resume"
      - "cv"
      - "personal-website"
    topics:
      - "portfolio"
      - "personal-website"
      - "showcase"
      - "profile"
      - "resume"
      - "cv"
      - "personal"

  "System Administration":
    description: "System administration tools, scripts, and configurations"
    keywords:
      - "sysadmin"
      - "system-administration"
      - "server"
      - "linux"
      - "unix"
      - "configuration"
      - "dotfiles"
      - "shell"
      - "bash"
      - "powershell"
    topics:
      - "sysadmin"
      - "system-administration"
      - "linux"
      - "unix"
      - "shell"
      - "bash"
      - "powershell"
      - "dotfiles"
      - "configuration"
      - "server"

  "Mobile & Cross-Platform":
    description: "Mobile development and cross-platform applications"
    keywords:
      - "mobile"
      - "android"
      - "ios"
      - "react-native"
      - "flutter"
      - "xamarin"
      - "cross-platform"
      - "hybrid"
    topics:
      - "mobile"
      - "android"
      - "ios"
      - "react-native"
      - "flutter"
      - "xamarin"
      - "cross-platform"
      - "mobile-development"
      - "mobile-app"

  "Design & Frontend":
    description: "UI/UX design, frontend frameworks, and web design resources"
    keywords:
      - "design"
      - "ui"
      - "ux"
      - "frontend"
      - "css"
      - "html"
      - "react"
      - "vue"
      - "angular"
      - "web-design"
      - "responsive"
    topics:
      - "design"
      - "ui"
      - "ux"
      - "frontend"
      - "css"
      - "html"
      - "react"
      - "vue"
      - "angular"
      - "web-design"
      - "responsive-design"
      - "tailwindcss"
      - "bootstrap"

# Default category for repositories that don't match any specific criteria
default_category: "Development & Programming"

# Minimum confidence score for categorization (0.0 to 1.0)
min_confidence: 0.3

# Priority order for categories (higher priority wins in case of ties)
category_priority:
  - "ML & AI"
  - "DevOps & Cloud"
  - "Mobile & Cross-Platform"
  - "Games & Entertainment"
  - "Design & Frontend"
  - "Tools & Utilities"
  - "System Administration"
  - "Learning & Education"
  - "Portfolio & Showcase"
  - "Open Source Projects"
  - "Development & Programming"