name: Update Credly Badges

on:
    schedule:
        - cron: "0 0 * * *" # every day at midnight UTC
    workflow_dispatch:

permissions:
    contents: write

jobs:
    update-badges:
        name: Update README with Credly Badges
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              
            - name: Update Credly Badges
              run: |
                # Fetch Credly badges using curl and update README
                echo "🏆 Fetching Credly badges for user: sagar-gupta.f8eb96cc"
                
                # Create a simple badge section (you can enhance this)
                cat > badge_section.txt << 'EOF'
                <!-- CREDLY-BADGES:START -->
                ![Credly Profile](https://img.shields.io/badge/Credly-Profile-orange?style=for-the-badge&logo=credly&logoColor=white&link=https://www.credly.com/users/sagar-gupta.f8eb96cc)
                <!-- CREDLY-BADGES:END -->
                EOF
                
                # Update README if it exists
                if [ -f "README.md" ]; then
                  # Check if badge section already exists
                  if grep -q "<!-- CREDLY-BADGES:START -->" README.md; then
                    # Replace existing section using awk
                    awk '
                    /<!-- CREDLY-BADGES:START -->/ { 
                      print; 
                      system("cat badge_section.txt | tail -n +2 | head -n -1"); 
                      skip=1; 
                      next 
                    }
                    /<!-- CREDLY-BADGES:END -->/ && skip { 
                      print; 
                      skip=0; 
                      next 
                    }
                    !skip { print }
                    ' README.md > README_temp.md && mv README_temp.md README.md
                  else
                    # Append to end of file
                    echo "" >> README.md
                    cat badge_section.txt >> README.md
                  fi
                  
                  # Clean up temp file
                  rm -f badge_section.txt
                  
                  echo "✅ Updated README.md with Credly badges"
                else
                  echo "❌ README.md not found"
                  exit 1
                fi
                
            - name: Commit changes
              run: |
                git config --local user.email "action@github.com"
                git config --local user.name "GitHub Action"
                
                if git diff --quiet; then
                  echo "No changes to commit"
                else
                  git add README.md
                  git commit -m "🏆 Update Credly badges [skip ci]"
                  git push
                  echo "✅ Changes committed and pushed"
                fi
