name: Update Credly Badges

on:
    schedule:
        - cron: "0 2 * * *"
    workflow_dispatch:

permissions:
    contents: write

jobs:
    update-badges:
        name: Update README with Credly Badges
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Update Badges
              uses: pemtajo/badge-readme@main
              with:
                  CREDLY_USER: sagar-gupta.f8eb96cc
                  NUMBER_LAST_BADGES: 0
